name = "big-push-server"

compatibility_date = "2024-05-11"


main = "./src/index.ts"
logpush = true

[vars]
APNS_TOPIC = "com.k2fintech.big-messenger-dev"
SANDBOX = true
[[queues.consumers]]
queue = "push-queue"
max_batch_size = 1
max_batch_timeout = 0
max_retries = 1
max_concurrency = 10
